# Site settings
title: James Conroy portfolio
email: jamespc167@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  James Conroy's open source portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://you.github.io" # the base hostname & protocol for your site
twitter_username: jamesconroy
github_username:  jamesconroy

# Build settings
markdown: kramdown
