# Site settings
title: James P. Conroy
suhead: Full-stack Developer living in Chicago
email: jamespc167@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  James Conroy's open source portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://you.github.io" # the base hostname & protocol for your site
twitter_username: jamesconroy
github_username:  jamesconroy
linkedin_username: jamesconroy1
instagram_username: jamesconroy
jquery: /assets/js/jquery.js
maincss: /assets/css/main.css
phone: (610) 357-3677
location: Chicago, IL



# Build settings
markdown: kramdown
